use_frameworks!

platform :ios, '12.0'

target 'TeneasyFaceDetectSDK_Example' do
  pod 'TeneasyFaceDetectSDK', :path => '../'
  #pod 'TeneasyFaceDetectSDK', :git => 'https://github.com/tianxuefeng/TeneasyFaceDetectSDK.git'
  target 'TeneasyFaceDetectSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer| #解决Xcode14编译问题
        installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                        config.build_settings["DEVELOPMENT_TEAM"] = "TJM8W7CS7Y"
                        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                end
            end
        end
end
