use_frameworks!

platform :ios, '10.0'

target 'TeneasyFaceDetectSDK_Example' do
  pod 'TeneasyFaceDetectSDK', :path => '../'

  target 'TeneasyFaceDetectSDK_Tests' do
    inherit! :search_paths

    
  end
end
